name: ilios
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - numpy=1.14.5
  - boto3=1.9.82
  - scikit-learn=0.19.1
  - scikit-image=0.13.1
  - scipy=1.1.0
  - tensorflow-gpu=1.12.0
  - matplotlib=2.2.2
